// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package system

import (
	"context"
)

// 系统基础服务
type SystemService interface {
	SendVerifyCode(ctx context.Context, req *SendVerifyCodeReq) (r *SendVerifyCodeResp, err error)

	CheckVerifyCode(ctx context.Context, req *CheckVerifyCodeReq) (r *CheckVerifyCodeResp, err error)
}
