// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package basicuser

import (
	"context"
)

// 基础用户相关接口
type BasicUserService interface {
	BasicUserRegister(ctx context.Context, req *BasicUserRegisterReq) (r *BasicUserRegisterResp, err error)

	BasicUserLogin(ctx context.Context, req *BasicUserLoginReq) (r *BasicUserLoginResp, err error)

	BasicUserResetPassword(ctx context.Context, req *BasicUserResetPasswordReq) (r *BasicUserResetPasswordResp, err error)
}
