// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package basicuser

import (
	"fmt"
	"github.com/xh-polaris/synapse-idl/hzcli/model/base"
)

type BasicUser struct {
	BasicUserId string `thrift:"basicUserId,1" form:"basicUserId" json:"basicUserId" query:"basicUserId"`
}

func NewBasicUser() *BasicUser {
	return &BasicUser{}
}

func (p *BasicUser) InitDefault() {
}

func (p *BasicUser) GetBasicUserId() (v string) {
	return p.BasicUserId
}

func (p *BasicUser) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUser(%+v)", *p)
}

/*
 基础用户相关API
*/
// 基础用户注册
type BasicUserRegisterReq struct {
	// 认证类型
	AuthType string `thrift:"authType,1" form:"authType" json:"authType" query:"authType"`
	// 认证id
	AuthId string `thrift:"authId,2" form:"authId" json:"authId" query:"authId"`
	// 扩展认证id
	ExtraAuthId *string `thrift:"extraAuthId,3,optional" form:"extraAuthId" json:"extraAuthId,omitempty" query:"extraAuthId"`
	// 认证凭证
	Verify string `thrift:"verify,4" form:"verify" json:"verify" query:"verify"`
	// 是否初始化密码
	Password *string   `thrift:"password,5,optional" form:"password" json:"password,omitempty" query:"password"`
	App      *base.App `thrift:"app,255" form:"app" json:"app" query:"app"`
}

func NewBasicUserRegisterReq() *BasicUserRegisterReq {
	return &BasicUserRegisterReq{}
}

func (p *BasicUserRegisterReq) InitDefault() {
}

func (p *BasicUserRegisterReq) GetAuthType() (v string) {
	return p.AuthType
}

func (p *BasicUserRegisterReq) GetAuthId() (v string) {
	return p.AuthId
}

var BasicUserRegisterReq_ExtraAuthId_DEFAULT string

func (p *BasicUserRegisterReq) GetExtraAuthId() (v string) {
	if !p.IsSetExtraAuthId() {
		return BasicUserRegisterReq_ExtraAuthId_DEFAULT
	}
	return *p.ExtraAuthId
}

func (p *BasicUserRegisterReq) GetVerify() (v string) {
	return p.Verify
}

var BasicUserRegisterReq_Password_DEFAULT string

func (p *BasicUserRegisterReq) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return BasicUserRegisterReq_Password_DEFAULT
	}
	return *p.Password
}

var BasicUserRegisterReq_App_DEFAULT *base.App

func (p *BasicUserRegisterReq) GetApp() (v *base.App) {
	if !p.IsSetApp() {
		return BasicUserRegisterReq_App_DEFAULT
	}
	return p.App
}

func (p *BasicUserRegisterReq) IsSetExtraAuthId() bool {
	return p.ExtraAuthId != nil
}

func (p *BasicUserRegisterReq) IsSetPassword() bool {
	return p.Password != nil
}

func (p *BasicUserRegisterReq) IsSetApp() bool {
	return p.App != nil
}

func (p *BasicUserRegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserRegisterReq(%+v)", *p)
}

type BasicUserRegisterResp struct {
	Resp      *base.Response `thrift:"resp,1" form:"resp" json:"resp" query:"resp"`
	Token     string         `thrift:"token,2" form:"token" json:"token" query:"token"`
	BasicUser *BasicUser     `thrift:"basicUser,255" form:"basicUser" json:"basicUser" query:"basicUser"`
}

func NewBasicUserRegisterResp() *BasicUserRegisterResp {
	return &BasicUserRegisterResp{}
}

func (p *BasicUserRegisterResp) InitDefault() {
}

var BasicUserRegisterResp_Resp_DEFAULT *base.Response

func (p *BasicUserRegisterResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return BasicUserRegisterResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *BasicUserRegisterResp) GetToken() (v string) {
	return p.Token
}

var BasicUserRegisterResp_BasicUser_DEFAULT *BasicUser

func (p *BasicUserRegisterResp) GetBasicUser() (v *BasicUser) {
	if !p.IsSetBasicUser() {
		return BasicUserRegisterResp_BasicUser_DEFAULT
	}
	return p.BasicUser
}

func (p *BasicUserRegisterResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *BasicUserRegisterResp) IsSetBasicUser() bool {
	return p.BasicUser != nil
}

func (p *BasicUserRegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserRegisterResp(%+v)", *p)
}

// 基础用户登录
type BasicUserLoginReq struct {
	AuthType string `thrift:"authType,1" form:"authType" json:"authType" query:"authType"`
	AuthId   string `thrift:"authId,2" form:"authId" json:"authId" query:"authId"`
	// 扩展认证id
	ExtraAuthId *string   `thrift:"extraAuthId,3,optional" form:"extraAuthId" json:"extraAuthId,omitempty" query:"extraAuthId"`
	Verify      string    `thrift:"verify,4" form:"verify" json:"verify" query:"verify"`
	App         *base.App `thrift:"app,255" form:"app" json:"app" query:"app"`
}

func NewBasicUserLoginReq() *BasicUserLoginReq {
	return &BasicUserLoginReq{}
}

func (p *BasicUserLoginReq) InitDefault() {
}

func (p *BasicUserLoginReq) GetAuthType() (v string) {
	return p.AuthType
}

func (p *BasicUserLoginReq) GetAuthId() (v string) {
	return p.AuthId
}

var BasicUserLoginReq_ExtraAuthId_DEFAULT string

func (p *BasicUserLoginReq) GetExtraAuthId() (v string) {
	if !p.IsSetExtraAuthId() {
		return BasicUserLoginReq_ExtraAuthId_DEFAULT
	}
	return *p.ExtraAuthId
}

func (p *BasicUserLoginReq) GetVerify() (v string) {
	return p.Verify
}

var BasicUserLoginReq_App_DEFAULT *base.App

func (p *BasicUserLoginReq) GetApp() (v *base.App) {
	if !p.IsSetApp() {
		return BasicUserLoginReq_App_DEFAULT
	}
	return p.App
}

func (p *BasicUserLoginReq) IsSetExtraAuthId() bool {
	return p.ExtraAuthId != nil
}

func (p *BasicUserLoginReq) IsSetApp() bool {
	return p.App != nil
}

func (p *BasicUserLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserLoginReq(%+v)", *p)
}

type BasicUserLoginResp struct {
	Resp      *base.Response `thrift:"resp,1" form:"resp" json:"resp" query:"resp"`
	Token     string         `thrift:"token,2" form:"token" json:"token" query:"token"`
	New       bool           `thrift:"new,3" form:"new" json:"new" query:"new"`
	BasicUser *BasicUser     `thrift:"basicUser,255" form:"basicUser" json:"basicUser" query:"basicUser"`
}

func NewBasicUserLoginResp() *BasicUserLoginResp {
	return &BasicUserLoginResp{}
}

func (p *BasicUserLoginResp) InitDefault() {
}

var BasicUserLoginResp_Resp_DEFAULT *base.Response

func (p *BasicUserLoginResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return BasicUserLoginResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *BasicUserLoginResp) GetToken() (v string) {
	return p.Token
}

func (p *BasicUserLoginResp) GetNew() (v bool) {
	return p.New
}

var BasicUserLoginResp_BasicUser_DEFAULT *BasicUser

func (p *BasicUserLoginResp) GetBasicUser() (v *BasicUser) {
	if !p.IsSetBasicUser() {
		return BasicUserLoginResp_BasicUser_DEFAULT
	}
	return p.BasicUser
}

func (p *BasicUserLoginResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *BasicUserLoginResp) IsSetBasicUser() bool {
	return p.BasicUser != nil
}

func (p *BasicUserLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserLoginResp(%+v)", *p)
}

// 修改密码
type BasicUserResetPasswordReq struct {
	NewPassword string `thrift:"newPassword,1" form:"newPassword" json:"newPassword" query:"newPassword"`
	// 重置码
	ResetKey *string   `thrift:"resetKey,2,optional" form:"resetKey" json:"resetKey,omitempty" query:"resetKey"`
	App      *base.App `thrift:"app,255" form:"app" json:"app" query:"app"`
}

func NewBasicUserResetPasswordReq() *BasicUserResetPasswordReq {
	return &BasicUserResetPasswordReq{}
}

func (p *BasicUserResetPasswordReq) InitDefault() {
}

func (p *BasicUserResetPasswordReq) GetNewPassword() (v string) {
	return p.NewPassword
}

var BasicUserResetPasswordReq_ResetKey_DEFAULT string

func (p *BasicUserResetPasswordReq) GetResetKey() (v string) {
	if !p.IsSetResetKey() {
		return BasicUserResetPasswordReq_ResetKey_DEFAULT
	}
	return *p.ResetKey
}

var BasicUserResetPasswordReq_App_DEFAULT *base.App

func (p *BasicUserResetPasswordReq) GetApp() (v *base.App) {
	if !p.IsSetApp() {
		return BasicUserResetPasswordReq_App_DEFAULT
	}
	return p.App
}

func (p *BasicUserResetPasswordReq) IsSetResetKey() bool {
	return p.ResetKey != nil
}

func (p *BasicUserResetPasswordReq) IsSetApp() bool {
	return p.App != nil
}

func (p *BasicUserResetPasswordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserResetPasswordReq(%+v)", *p)
}

type BasicUserResetPasswordResp struct {
	Resp *base.Response `thrift:"resp,1" form:"resp" json:"resp" query:"resp"`
}

func NewBasicUserResetPasswordResp() *BasicUserResetPasswordResp {
	return &BasicUserResetPasswordResp{}
}

func (p *BasicUserResetPasswordResp) InitDefault() {
}

var BasicUserResetPasswordResp_Resp_DEFAULT *base.Response

func (p *BasicUserResetPasswordResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return BasicUserResetPasswordResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *BasicUserResetPasswordResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *BasicUserResetPasswordResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BasicUserResetPasswordResp(%+v)", *p)
}
