// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package basicuser

import (
	"context"
	"github.com/xh-polaris/synapse-idl/hzcli/model/thirdparty"
)

type ThirdPartyService interface {
	ThirdPartyLogin(ctx context.Context, req *thirdparty.ThirdPartyLoginReq) (r *thirdparty.ThirdPartyLoginResp, err error)
}
