// Code generated by hertz generator.

package basic_user_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
}

type BasicUserServiceClient struct {
	client *cli
}

func NewBasicUserServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &BasicUserServiceClient{
		client: cli,
	}, nil
}

var defaultClient, _ = NewBasicUserServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewBasicUserServiceClient("", ops...)
	return
}
