// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package synapse

import (
	"github.com/xh-polaris/synapse-idl/hzcli/model/basicuser"
	"github.com/xh-polaris/synapse-idl/hzcli/model/system"
)

type SystemService interface {
	system.SystemService
}

type BasicUserService interface {
	basicuser.BasicUserService
}
